# Generated by Django 3.0.3 on 2020-11-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater', models.CharField(choices=[('customer', 'Customer'), ('service_provider', 'Service Provider')], default='customer', max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Order')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Customer')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.ServiceProvider')),
            ],
        ),
    ]
