# Generated by Django 3.0.6 on 2020-09-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.CharField(choices=[('customer', 'Customer'), ('service_provider', 'Service Provider')], default='notset', max_length=100),
        ),
    ]
