# Generated by Django 3.0.6 on 2020-09-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingApp', '0002_rating_rater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.CharField(choices=[('customer', 'Customer'), ('service_provider', 'Service Provider')], default='customer', max_length=100),
        ),
    ]
