# Generated by Django 3.0.3 on 2020-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YenePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=100)),
                ('buyer_id', models.CharField(max_length=500)),
                ('marchant_order_id', models.CharField(max_length=500)),
                ('marchant_id', models.CharField(max_length=500)),
                ('merchant_code', models.CharField(max_length=500)),
                ('transaction_code', models.CharField(max_length=500)),
                ('transaction_id', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=1000)),
            ],
        ),
    ]
