# Generated by Django 3.0.3 on 2020-10-31 17:17

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('is_online', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_booking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_lng', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('houseNo', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalRemark', models.TextField()),
                ('paymentType', models.CharField(choices=[('cash', 'Cash'), ('paypal', 'Paypal')], max_length=20)),
                ('scheduleType', models.CharField(choices=[('now', 'Now'), ('later', 'Later')], max_length=20)),
                ('scheduleDate', models.DateTimeField()),
                ('orderStatus', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('go_to_customer', 'Go to customer'), ('arrived', 'Arrived'), ('start_work', 'Start work'), ('completed', 'Completed')], default='pending', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Customer')),
                ('deliveryAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Location')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to='icon/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('serviceTitle',),
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subServiceTitle', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Service')),
            ],
            options={
                'ordering': ('subServiceTitle',),
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('is_online', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default='', max_length=10)),
                ('workingRadius', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Jobs')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='serviceProvider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='serviceProvider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='subService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.SubService'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
