# Generated by Django 3.0.3 on 2020-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_onetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='postal',
            field=models.CharField(default='', max_length=100),
        ),
    ]
