# Generated by Django 3.0.3 on 2020-10-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_location_postal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTest',
        ),
    ]
