# Generated by Django 3.0.3 on 2020-10-31 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('service_provider', 'Service Provider')], default='notset', max_length=100)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Customer')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.ServiceProvider')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
